// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequestToCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRequestToCollection'](arg1, arg2, arg3);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteSavedRequest(arg1) {
  return window['go']['main']['App']['DeleteSavedRequest'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function UpdateSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedRequest'](arg1, arg2, arg3);
}
