// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRequestToCollection(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<models.SavedRequest>;

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string):Promise<void>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:models.RequestPayload):Promise<models.ResponseResult>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<void>;
